export enum PagesActions {
    SET_PAGE = "SET_PAGE",
    DELETE_PAGE = "DELETE_PAGE",
    SET_STATUS = "SET_STATUS",
    SET_NAME_PAGE = "SET_NAME_PAGE"
}

export enum FilesActions {
    SET_FILE = "SET_FILE",
    DELETE_FILE = "DELETE_FILE",
    SET_NAME_FILE = "SET_NAME_FILE"
}

export enum AuthActions {
    REGISTRATION_USER = "REGISTRATION_USER",
    LOGIN_USER = "LOGIN_USER",
    LOGOUT_USER = "LOGOUT_USER",
    SET_STATUS_AUTH = "SET_STATUS_AUTH"
}